### ISSUE TITLE
Unable to capture full page screenshot for few websites

### ISSUE THREAD

**Issue by Zarmeena** [PyWizards/Selenium_Screenshot#1]
I have to extract the screenshot of the elements in a web page (including the elements that are at the bottom of the page , for which scrolling is required)

I tried using the following code but it's unable to generate the screenshot for the whole page:

**from Screenshot import Screenshot_Clipping
from selenium import webdriver

ob=Screenshot_Clipping.Screenshot()
options = webdriver.ChromeOptions()
options.headless = True
driver = webdriver.Chrome(options=options)

url = "https://www.google.com/"

driver.get(url)

#element=driver.find_element_by_class_name('signup-prompt')
element=driver.find_element_by_xpath('//*[@id="fsr"]/a[1]')

img_url=ob.get_element(driver, element, r'.')
print(img_url)

driver.close()

driver.quit()**

The image of selected element is clipped. Could you please let me know if there is any workaround to achieve this.

**Comment by sam4u3** [comment]
Can you share screenshot of you code and the elements which need to capture

**Comment by Zarmeena** [comment]
Have appended the code in the original post.
I have to capture all the elements of the page.I have used www.google.com in the code attached.

**Comment by sam4u3** [comment]
Ok I am working on it... I will let you know once it's completed

**Comment by Zarmeena** [comment]
Thanks @sam4u3 . It would be great if you could also check on the performance of the script as it's taking too much time in scanning the whole page.
