### ISSUE TITLE
Not working with Grafana 

### ISSUE THREAD

**Issue by rjvtww** [PyWizards/Selenium_Screenshot#10]
**Describe the bug**
Not working properly with Grafana dashboards.

**To Reproduce**
An example site:

https://play.grafana.org/d/0KapoFkMk/1-new-features-in-v7-0?orgId=1&refresh=5s

**Expected behavior**
The script does not scroll down a dashboard, it only saves the viewport. This is in full page mode.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.02
 - Browser [e.g. chrome, safari]: Chrome
 - Version: 1

**Comment by rjvtww** [comment]
I made this work today. I would share the code but it looks really hacky (not a programmer).

The problem is that the window.scrollto doesn't work, as the window element does not contain the actual scrollable container.

total_height = driver.execute_script("return document.querySelector('.dashboard-container .layout').clientHeight")

driver.execute_script("view = document.getElementsByClassName('view')") 
#view[0] is the scrollable container. From here on, replace window with view[0]
driver.execute_script("view[0].scrollTo(0, 0)")

Hope this helps!

**Comment by sam4u3** [comment]
Hi ,

Will look into this, and update the same
