### ISSUE TITLE
ModuleNotFound on ubuntu server.

### ISSUE THREAD

**Issue by discorapp** [PyWizards/Selenium_Screenshot#20]
**Describe the bug**
After installing using pip3 python3 returns ModuleNotFoundError: No module named 'Screenshot'

**To Reproduce**
1. Install Selenium-Screenshot using pip3 on Ubuntu server
2. Import the Screenshot-Clipping from it
3. python3 the file

**Expected behavior**
A program would run without an error

**Screenshots**
![image](https://user-images.githubusercontent.com/87983820/180648550-47dceff6-3557-4dc1-af5b-0c7f9e02eddb.png)
![image](https://user-images.githubusercontent.com/87983820/180648558-344fe06c-83db-4a30-8541-77a0234951e5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server
 - Browser Firefox webdriver

**Comment by Splint3r7** [comment]
Fix that worked for me:

```
$ git clone https://github.com/PyWizards/Selenium_Screenshot.git
$ cd Selenium_Screenshot
$ python3 setup.py install
```
