### ISSUE TITLE
Last part of the screenshot is duplicated

### ISSUE THREAD

**Issue by agsoto** [PyWizards/Selenium_Screenshot#23]
**Bug description**
There's a tiny miscalculation when pasting the last part of the image when the last remaining step of the scroll does not fit the entire viewport.

**To Reproduce**
1. Create a instance of the Screenshot class
2. Call the full_screenshot method setting the multi_images flag to true
3. See the resulting image

**Expected behavior**
The image should not have repeated parts it should be visualized as the regular webpage in the browser.

**Screenshot**

<img src="https://user-images.githubusercontent.com/70116396/214793332-9733ba05-f1d6-471f-8300-181f98b10f7a.png" alt="Bad screenshot" width="300"/>

**Desktop**
 - OS: Windows 11
 - Browser: Chromium

**Comment by chxlium** [comment]
Hello, it´s still happening to me when the page is long and I need to scroll down
