### ISSUE TITLE
Feature request : Add hide_elements argument to get_element function

### ISSUE THREAD

**Issue by marrakchino** [PyWizards/Selenium_Screenshot#8]
**Is your feature request related to a problem? Please describe.**
It would be nice to call `get_element` with an additional argument that specifies a list of elements to hide, that would be included in the call to `full_Screenshot`

**Describe the solution you'd like**
Add an optional parameter to `get_element`, initialized to [] by default, and change the call to `full_Screenshot` by adding this parameter.

I can submit a PR if this is interesting

**Comment by sam4u3** [comment]
Yes we very much appreciated it if you can submit the pull request.
